default: &default
  adapter: postgresql
  database: meal_planner
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: meal_planner
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: meal_planner_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: meal_planner
  pool: 5
  timeout: 5000
